# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-19 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import museo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('imatge', models.ImageField(upload_to=museo.models.upload_location)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('n_inventari', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('nom', models.CharField(default='', max_length=250)),
                ('n_peces', models.IntegerField(blank=True, null=True)),
                ('utilitat', models.CharField(blank=True, max_length=250, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=250, null=True)),
                ('exposada', models.BooleanField(default=False)),
                ('propietari', models.CharField(blank=True, max_length=250, null=True)),
                ('donacio', models.BooleanField(default=False)),
                ('n_diposit_material', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcio_us', models.TextField(blank=True, null=True)),
                ('mesura_llarg_alt', models.CharField(blank=True, help_text='En (cm)', max_length=250, null=True)),
                ('mesura_ample', models.CharField(blank=True, help_text='En (cm)', max_length=250, null=True)),
                ('mesura_grueso_fons', models.CharField(blank=True, help_text='En (cm)', max_length=250, null=True)),
                ('mesura_diametre', models.CharField(blank=True, help_text='En (cm)', max_length=250, null=True)),
                ('material_fabricacio', models.CharField(blank=True, max_length=250, null=True)),
                ('tecnica_fabricacio', models.CharField(blank=True, max_length=250, null=True)),
                ('any_fabricacio', models.CharField(blank=True, max_length=250, null=True)),
                ('any_us', models.CharField(blank=True, max_length=250, null=True)),
                ('restauracio', models.CharField(blank=True, max_length=250, null=True)),
                ('estat_conservacio', models.CharField(blank=True, max_length=250, null=True)),
                ('data_catalogacio', models.CharField(blank=True, max_length=250, null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museo_classe', to='museo.Classe')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='museo',
            name='tipus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museo_tipus', to='museo.Tipus'),
        ),
        migrations.AddField(
            model_name='imatge',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imatges', to='museo.Museo'),
        ),
    ]
