# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-18 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipus',
            options={'ordering': ['nom'], 'verbose_name': 'Tipus', 'verbose_name_plural': 'Tipus'},
        ),
    ]
