# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='n_peces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
