# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-15 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0002_auto_20190214_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='nom',
            field=models.CharField(default='', max_length=250),
        ),
    ]
