# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-15 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0003_auto_20190215_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museo',
            name='tipus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museo_tipus', to='museo.Tipus'),
        ),
    ]
