# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-18 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museo', '0005_auto_20190218_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imatge',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imatges', to='museo.Museo'),
        ),
    ]
