# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', upload_to=profiles.models.upload_location, width_field='width_field'),
        ),
    ]
