# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-24 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180506_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telefono',
            new_name='telefono_fijo',
        ),
    ]
