# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-24 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_telefono_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='poblacion',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
