# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=250, null=True, unique=True),
        ),
    ]
