# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', height_field='height_field', upload_to=profiles.models.upload_location, validators=[profiles.validators.file_size], width_field='width_field'),
        ),
    ]
