# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-04 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0004_auto_20181004_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='group',
        ),
    ]
