# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionPresupuestaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aplicacion_presupuestaria', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['aplicacion_presupuestaria'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('base', models.CharField(blank=True, max_length=250, null=True)),
                ('iva', models.CharField(blank=True, max_length=250, null=True)),
                ('total', models.CharField(blank=True, max_length=250, null=True)),
                ('date_contract', models.DateField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, max_length=250, null=True)),
                ('objeto', models.TextField(blank=True, help_text='Necesidad a satisfacer / Objeto del contrato')),
                ('description', models.TextField(blank=True)),
                ('ejercicio', models.CharField(blank=True, max_length=250, null=True)),
                ('importe_recursos', models.CharField(blank=True, help_text='Importe de los recursos del presupuesto', max_length=250, null=True)),
                ('valor_estimado', models.CharField(blank=True, help_text='Valor estimado del contrato', max_length=250, null=True)),
                ('porcentaje', models.CharField(blank=True, help_text='% sobre los recursos', max_length=250, null=True)),
                ('decl_responsable', models.BooleanField(default=False, help_text='Declaración responsable de no incurrir en prohibición de contratar')),
                ('certificado_hacienda', models.BooleanField(default=False, help_text='Certificado Hacienda de estar al corriente de sus obligaciones')),
                ('aplic_presupuestaria', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_aplicacion_presupuestaria', to='contracts.AplicacionPresupuestaria')),
            ],
            options={
                'verbose_name': 'Contratos',
                'verbose_name_plural': 'Contratos',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('dni', models.CharField(max_length=250)),
                ('email', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('pagina_web', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('provincia', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('poblacion', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cpv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cpv', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['cpv'],
            },
        ),
        migrations.CreateModel(
            name='Organos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Organos',
                'verbose_name_plural': 'Organos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_contractor', to='contracts.Contractor'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpv',
            field=models.ManyToManyField(blank=True, related_name='cpvs', to='contracts.Cpv'),
        ),
        migrations.AddField(
            model_name='contract',
            name='organo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplic_presup_organo', to='contracts.Organos'),
        ),
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_contract', to='contracts.TypeContract'),
        ),
    ]
