# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cpv', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['cpv'],
            },
        ),
        migrations.RemoveField(
            model_name='aplicacionpresupuestaria',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='aplicacionpresupuestaria',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='aplicacionpresupuestaria',
            name='importe_recursos',
        ),
        migrations.RemoveField(
            model_name='aplicacionpresupuestaria',
            name='organo',
        ),
        migrations.RemoveField(
            model_name='aplicacionpresupuestaria',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='aplicacionpresupuestaria',
            name='valor_estimado',
        ),
        migrations.AddField(
            model_name='contract',
            name='ejercicio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='importe_recursos',
            field=models.CharField(blank=True, help_text='Importe de los recursos del presupuesto', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='organo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplic_presup_organo', to='contracts.Organos'),
        ),
        migrations.AddField(
            model_name='contract',
            name='porcentaje',
            field=models.CharField(blank=True, help_text='% sobre los recursos', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='valor_estimado',
            field=models.CharField(blank=True, help_text='Valor estimado del contrato', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='color',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='contractor',
            name='direccion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='contractor',
            name='poblacion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='contractor',
            name='provincia',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='contractor',
            name='telefono',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cpv',
        ),
        migrations.AddField(
            model_name='contract',
            name='cpv',
            field=models.ManyToManyField(blank=True, related_name='cpvs', to='contracts.Cpv'),
        ),
    ]
