# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicacionpresupuestaria',
            old_name='procentaje',
            new_name='porcentaje',
        ),
    ]
