# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-09 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20181226_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['date_contract', 'contractor', 'contractor__dni'], 'verbose_name': 'Contratos', 'verbose_name_plural': 'Contratos'},
        ),
    ]
