# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20181008_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_contractor', to='contracts.Contractor'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_contract', to='contracts.TypeContract'),
        ),
    ]
