# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20181207_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='identificador',
        ),
    ]
