# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20181008_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='aplicacionpresupuestaria',
            name='organo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplic_presup_organo', to='contracts.Organos'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='objeto',
            field=models.TextField(blank=True, help_text='Necesidad a satisfacer / Objecto del contrato'),
        ),
    ]
