# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20181008_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='base',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='iva',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
