# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-01 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
        ('contracts', '0003_auto_20190109_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_tercero', to='terceros.Terceros'),
        ),
    ]
