# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20181008_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='objeto',
            field=models.TextField(blank=True, help_text='Necesidad a satisfacer / Objeto del contrato'),
        ),
    ]
