# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='color',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='poblacion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
