# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20181008_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organos',
            options={'ordering': ['name'], 'verbose_name': 'Organos', 'verbose_name_plural': 'Organos'},
        ),
    ]
