# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20181207_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='certificado_hacienda',
            field=models.BooleanField(default=False, help_text='Certificado Hacienda de estar al corriente de sus obligaciones'),
        ),
        migrations.AddField(
            model_name='contract',
            name='decl_responsable',
            field=models.BooleanField(default=False, help_text='Declaración responsable de no incurrir en prohibición de contratar'),
        ),
    ]
