# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20181008_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'ordering': ['name']},
        ),
    ]
