# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_contratante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['date_contract', 'contratante', 'contratante__identificacion'], 'verbose_name': 'Contratos', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractor',
        ),
    ]
