# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20181008_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
