# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='aplicacion_presupuestaria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='cpv',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='duracion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='objeto',
            field=models.TextField(blank=True),
        ),
    ]
