# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terceros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identificacion', models.CharField(blank=True, help_text='NIF/CIF/Otro/Ninguna', max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('movil', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('pagina_web', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_via', models.CharField(blank=True, help_text='Calle/Avenida/Plaza...', max_length=255, null=True)),
                ('nombre_via', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=255, null=True)),
                ('bloque', models.CharField(blank=True, max_length=255, null=True)),
                ('escalera', models.CharField(blank=True, max_length=255, null=True)),
                ('planta', models.CharField(blank=True, max_length=255, null=True)),
                ('puerta', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['-nombre'],
            },
        ),
    ]
