# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terceros',
            options={'ordering': ['nombre'], 'verbose_name': 'Tercero', 'verbose_name_plural': 'Terceros'},
        ),
    ]
