# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
