# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, default=None, max_length=250, null=True, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, default=None, max_length=250, null=True, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Ente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, default=None, max_length=250, null=True, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subvenciones.Area')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, default=None, max_length=250, null=True, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Subvencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('nombre', models.TextField(default='')),
                ('procedimiento', models.TextField(blank=True)),
                ('bases', models.TextField(blank=True)),
                ('solicitud', models.TextField(blank=True)),
                ('cuantia_inicial', models.CharField(blank=True, max_length=250, null=True)),
                ('cuantia_final', models.CharField(blank=True, max_length=250, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('drive', models.TextField(blank=True, null=True)),
                ('gestiona_expediente', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_carpeta_drive', models.TextField(blank=True, null=True)),
                ('colectivo', models.ManyToManyField(blank=True, to='subvenciones.Colectivo')),
                ('ente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subvenciones.Ente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subvenciones.Estado')),
                ('se_relaciona_con', models.ManyToManyField(blank=True, default='', related_name='_subvencion_se_relaciona_con_+', to='subvenciones.Subvencion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subvencion',
                'verbose_name_plural': 'Subvenciones',
                'ordering': ['fin'],
            },
        ),
        migrations.AddField(
            model_name='like',
            name='subvencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subvenciones.Subvencion'),
        ),
        migrations.AddField(
            model_name='comment',
            name='for_subvencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subvenciones.Subvencion'),
        ),
    ]
