# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='for_subvencion',
            new_name='subvencion',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='contenido',
            field=models.TextField(default=''),
        ),
    ]
