# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-07 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subvenciones', '0002_auto_20180504_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='subvencion_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
