# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subvenciones', '0003_subvencion_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='responsable',
            field=models.ManyToManyField(related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
