# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0005_auto_20180508_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subvenciones.Area'),
        ),
        migrations.AlterField(
            model_name='subvencion',
            name='ente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subvenciones.Ente'),
        ),
    ]
