# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 16:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0014_auto_20180514_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subvencion',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ente', chained_model_field='ente', default='', on_delete=django.db.models.deletion.CASCADE, to='subvenciones.Area'),
        ),
    ]
