# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0015_auto_20180517_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='impreso',
            field=models.BooleanField(default=False),
        ),
    ]
