# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-22 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0016_subvencion_impreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subvencion',
            old_name='inicio',
            new_name='fecha_publicacion',
        ),
    ]
