# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-10 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0018_subvencion_fecha_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='color',
            field=models.CharField(default='#fff', max_length=250),
        ),
    ]
