# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-03 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0019_estado_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='cuantia_solicitada',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
