# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0020_subvencion_cuantia_solicitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='explicacion_justificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subvencion',
            name='fin_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subvencion',
            name='fin_justificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subvencion',
            name='incio_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
