# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-27 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0022_subvencion_leimotiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subvencion',
            name='sin_cuantia',
            field=models.BooleanField(default=False),
        ),
    ]
