# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subvenciones', '0023_auto_20180927_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvencion',
            name='porcentaje_subvencionable',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
