# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-02 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('edad', models.CharField(blank=True, max_length=250, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=250, null=True)),
                ('cuantia', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_pagado', models.DateField(blank=True, null=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
