# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-10 09:22
from __future__ import unicode_literals

import UPR.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('capital', models.CharField(blank=True, max_length=250, null=True)),
                ('habitantes', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('km_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_componentes', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_comentario', models.TextField(blank=True, null=True)),
                ('imatge_componente', models.ImageField(blank=True, null=True, upload_to=UPR.models.upload_location)),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='GrupoComponentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_grupo_componentes', models.CharField(blank=True, max_length=250, null=True)),
                ('position_grupo_componentes', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=True)),
                ('taller', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoMaquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('numero_inventario', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('capataz_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incidencias', models.ManyToManyField(blank=True, related_name='tipo_incidencia', to='UPR.Incidencias')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoMaquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre_obra', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo_INE', models.CharField(blank=True, max_length=250, null=True)),
                ('orden_noel', models.PositiveSmallIntegerField(default=0)),
                ('comarca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPR.Comarca')),
            ],
            options={
                'verbose_name': 'Poblacion',
                'verbose_name_plural': 'Poblaciones',
                'ordering': ['codigo_INE'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuebloTermporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre_temporada', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevisionesTemporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre_revision', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre_temporada', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(blank=True, max_length=250, null=True)),
                ('img_maquina', models.ImageField(blank=True, null=True, upload_to=UPR.models.upload_location)),
                ('url_tienda_maquina', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pueblotermporada',
            name='poblacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poblacionTemporada', to='UPR.Temporada'),
        ),
        migrations.AddField(
            model_name='movimientoobra',
            name='nombre_obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombreObra', to='UPR.Obra'),
        ),
        migrations.AddField(
            model_name='movimientomaquinaria',
            name='poblacion_mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombrePoblacion', to='UPR.Poblacion'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='maquina_poblacion',
            field=models.ManyToManyField(blank=True, related_name='nombre_poblacion', to='UPR.MovimientoMaquinaria'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='obra',
            field=models.ManyToManyField(blank=True, related_name='rel_nombre_obra', to='UPR.MovimientoObra'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='tipo_maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_maquinas', to='UPR.TipoMaquina'),
        ),
        migrations.AddField(
            model_name='mantenimientomaquinaria',
            name='nombre_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombreRevision', to='UPR.RevisionesTemporada'),
        ),
        migrations.AddField(
            model_name='mantenimientomaquinaria',
            name='numero_incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numeroIncidencia', to='UPR.Incidencias'),
        ),
        migrations.AddField(
            model_name='mantenimientomaquinaria',
            name='numero_maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numeroMaquina', to='UPR.Maquina'),
        ),
        migrations.AddField(
            model_name='incidencias',
            name='mantenimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_mantenimiento', to='UPR.RevisionesTemporada'),
        ),
        migrations.AddField(
            model_name='incidencias',
            name='tipo_incidencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_componente', to='UPR.Componentes'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='grupo_componentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_componentes', to='UPR.GrupoComponentes'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='tipo_maquina',
            field=models.ManyToManyField(blank=True, related_name='tipo_maquina_componente', to='UPR.TipoMaquina'),
        ),
        migrations.AddField(
            model_name='comarca',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPR.Provincia'),
        ),
    ]
