# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-13 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='fechaCerrado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
