# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='fechaCerrado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientomaquinaria',
            name='fecha_movimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movimientoobra',
            name='fecha_movimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='revisionestemporada',
            name='fecha_revision',
            field=models.DateField(null=True),
        ),
    ]
