# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuebloAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha_movimiento', models.DateField(null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('poblacion_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombrePoblacionAsignado', to='UPR.Poblacion')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='maquina',
            name='pueblo_asignado',
            field=models.ManyToManyField(blank=True, related_name='rel_pueblo_asignado', to='UPR.PuebloAsignado'),
        ),
    ]
