# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0002_auto_20190904_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='opcion_select_componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcion_select_componente', to='UPR.Componentes'),
        ),
    ]
