# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0002_auto_20190910_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puebloasignado',
            name='poblacion_asignada',
        ),
        migrations.AddField(
            model_name='puebloasignado',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pueblo_asignado', to='UPR.Poblacion'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='pueblo_asignado',
            field=models.ManyToManyField(blank=True, related_name='pueblo_asignado', to='UPR.PuebloAsignado'),
        ),
    ]
