# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0002_maquina_capataz_responsable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentes',
            options={'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
    ]
