# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0002_incidencias_fechacerrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='fechaCerrado',
            field=models.DateField(null=True),
        ),
    ]
