# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0003_auto_20190911_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='usuario',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
