# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0003_auto_20190613_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientomaquinaria',
            name='fecha_movimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movimientoobra',
            name='fecha_movimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='revisionestemporada',
            name='fecha_revision',
            field=models.DateField(null=True),
        ),
    ]
