# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-11 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UPR', '0004_incidencias_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencias',
            name='usuario',
        ),
        migrations.AddField(
            model_name='incidencias',
            name='capataz_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
