# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0004_componentes_tipo_maquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentes',
            name='tipo_maquina',
        ),
        migrations.AddField(
            model_name='componentes',
            name='tipo_maquina',
            field=models.ManyToManyField(blank=True, related_name='tipo_maquina_componente', to='UPR.TipoMaquina'),
        ),
    ]
