# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-05 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0004_auto_20190904_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencias',
            name='campo_componente',
        ),
        migrations.RemoveField(
            model_name='incidencias',
            name='opcion_select_componente',
        ),
    ]
