# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0005_auto_20190905_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='campo_componente',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='incidencias',
            name='opcion_select_componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opcion_select_componente', to='UPR.OpcionesComponente'),
        ),
    ]
