# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-04 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0006_auto_20190617_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionesComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='componentes',
            name='opciones_componente',
            field=models.ManyToManyField(blank=True, related_name='opciones_componente', to='UPR.OpcionesComponente'),
        ),
    ]
