# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-09 11:30
from __future__ import unicode_literals

import UPR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0007_auto_20190509_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentes',
            name='imatge_componente',
            field=models.ImageField(blank=True, null=True, upload_to=UPR.models.upload_location),
        ),
    ]
