# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0008_incidencias_n_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='fechaCerrado',
            field=models.DateField(default=False),
        ),
    ]
