# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0008_auto_20190509_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoComponentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tipo_grupo_componentes', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='componentes',
            name='grupo_componentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_componentes', to='UPR.GrupoComponentes'),
        ),
    ]
