# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0011_grupocomponentes_position_grupo_componentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
                ('dc', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Poblacion',
                'verbose_name_plural': 'Poblaciones',
                'ordering': ['codigo'],
            },
        ),
    ]
