# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0013_auto_20190516_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='comarca',
            name='capital',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='comarca',
            name='habitantes',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='comarca',
            name='km_cuadrados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='comarca',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UPR.Provincia'),
        ),
    ]
