# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0015_auto_20190516_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='maquina_poblacion',
        ),
    ]
