# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0016_remove_maquina_maquina_poblacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='funcionamiento',
            field=models.BooleanField(default=True),
        ),
    ]
