# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0017_incidencias_funcionamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencias',
            name='funcionamiento',
        ),
    ]
