# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-17 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0019_incidencias_operativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencias',
            old_name='operativo',
            new_name='cerrado',
        ),
    ]
