# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0022_remove_componentes_tipo_opciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='revision_fin_temporada_2019',
            field=models.BooleanField(default=False),
        ),
    ]
