# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-23 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0023_incidencias_revision_fin_temporada_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='poblacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poblacion', to='UPR.Poblacion'),
        ),
    ]
