# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0024_maquina_poblacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoMaquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='maquina',
            name='poblacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombrePoblacionMaquina', to='UPR.Poblacion'),
        ),
        migrations.AddField(
            model_name='movimientomaquinaria',
            name='numero_inventario_mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numeroInventario', to='UPR.Maquina'),
        ),
        migrations.AddField(
            model_name='movimientomaquinaria',
            name='poblacion_mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombrePoblacion', to='UPR.Poblacion'),
        ),
    ]
