# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-24 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0026_revisionestemporada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientomaquinaria',
            options={'ordering': ['-fecha_movimiento']},
        ),
    ]
