# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-24 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0027_auto_20190524_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencias',
            options={'ordering': ['fecha'], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
    ]
