# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-24 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0028_auto_20190524_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencias',
            name='revision_fin_temporada_2019',
        ),
    ]
