# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-24 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0029_remove_incidencias_revision_fin_temporada_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisionestemporada',
            old_name='fecha_revisión',
            new_name='fecha_revision',
        ),
        migrations.AddField(
            model_name='incidencias',
            name='mantenimientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_mantenimiento', to='UPR.RevisionesTemporada'),
        ),
    ]
