# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-27 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0032_mantenimientomaquinaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencias',
            options={'ordering': ['-fecha'], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
    ]
