# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0033_auto_20190527_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='poblacion',
        ),
        migrations.AlterField(
            model_name='movimientomaquinaria',
            name='poblacion_mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombre_poblacion', to='UPR.Poblacion'),
        ),
    ]
