# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0034_auto_20190528_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='poblacion',
            field=models.ManyToManyField(blank=True, null=True, related_name='nombrePoblacionMaquina', to='UPR.Poblacion'),
        ),
        migrations.AlterField(
            model_name='movimientomaquinaria',
            name='poblacion_mm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombrePoblacion', to='UPR.Poblacion'),
        ),
    ]
