# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0036_auto_20190528_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fecha_movimiento', models.DateField(blank=True, null=True)),
                ('nombre_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombreObra', to='UPR.Obra')),
                ('numero_inventario_obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numeroInventarioObra', to='UPR.Maquina')),
            ],
            options={
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
