# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-03 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0042_remove_maquina_poblacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='obra',
        ),
    ]
