# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0044_auto_20190605_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoobra',
            name='numero_inventario_obra',
        ),
        migrations.AddField(
            model_name='maquina',
            name='obra',
            field=models.ManyToManyField(blank=True, related_name='rel_nombre_obra', to='UPR.MovimientoObra'),
        ),
        migrations.AddField(
            model_name='movimientoobra',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
