# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-07 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPR', '0045_auto_20190607_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='taller',
            field=models.BooleanField(default=False),
        ),
    ]
