# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('metros_cuadrados', models.CharField(blank=True, max_length=250)),
                ('poligono', models.CharField(blank=True, max_length=250)),
                ('numero_parcela', models.CharField(blank=True, max_length=250)),
                ('comentarios', models.TextField(blank=True)),
                ('estado', models.ManyToManyField(blank=True, to='parcelas.Estado')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(blank=True, max_length=250)),
                ('nif', models.CharField(blank=True, max_length=250)),
                ('poblacion', models.CharField(blank=True, max_length=250)),
                ('calle', models.CharField(blank=True, max_length=250)),
                ('telefono_fijo', models.CharField(blank=True, max_length=250)),
                ('telefono_movil', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('comentarios', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SectorTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Sector Trabajo',
                'verbose_name_plural': 'Sectores de Trabajo',
                'ordering': ['sector'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sector_trabajo',
            field=models.ManyToManyField(blank=True, to='parcelas.SectorTrabajo'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='propietario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelas.Propietario'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='sector_trabajo',
            field=models.ManyToManyField(blank=True, to='parcelas.SectorTrabajo'),
        ),
    ]
