# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='apellidos2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
