# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0002_poblacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='poblacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelas.Poblacion'),
        ),
    ]
