# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-15 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0002_propietario_apellidos2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='nif',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
