# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0004_auto_20181010_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='poblacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parcelas.Poblacion'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='propietario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parcelas.Propietario'),
        ),
    ]
