# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-16 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelas', '0004_auto_20181015_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(blank=True, max_length=250)),
                ('apellidos2', models.CharField(blank=True, max_length=250)),
                ('nif', models.CharField(blank=True, max_length=250, unique=True)),
                ('poblacion', models.CharField(blank=True, max_length=250)),
                ('calle', models.CharField(blank=True, max_length=250)),
                ('telefono_fijo', models.CharField(blank=True, max_length=250)),
                ('telefono_movil', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('comentarios', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['-nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='user',
        ),
        migrations.AddField(
            model_name='parcela',
            name='propietario',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
