# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0008_auto_20181010_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='estado',
        ),
        migrations.AddField(
            model_name='parcela',
            name='estado',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='parcelas.Estado'),
            preserve_default=False,
        ),
    ]
