# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-17 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0009_parcela_estado_parcela_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='nif',
            field=models.CharField(blank=True, help_text='Ejemplo: 12345678-T', max_length=250, unique=True),
        ),
    ]
