# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0009_auto_20181011_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelas.Estado'),
        ),
    ]
