# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-16 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelas', '0013_parcela_kml'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoblacionesFavoritas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('favorito', models.BooleanField(default=False)),
                ('poblacion', models.ManyToManyField(blank=True, to='parcelas.Poblacion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poblaciones favoritas',
                'verbose_name_plural': 'Poblaciones favoritas',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Poblacion',
                'verbose_name_plural': 'Poblaciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='poblacion',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelas.Provincia'),
        ),
    ]
