# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-18 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0016_remove_propietario_poblacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='poblacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario_poblacion', to='parcelas.Poblacion'),
        ),
    ]
