# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-18 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0017_propietario_poblacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nombre'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AddField(
            model_name='poblacion',
            name='dc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
