# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-18 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0018_auto_20190118_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poblacionesfavoritas',
            name='poblacion',
            field=models.ManyToManyField(blank=True, related_name='poblacion', to='parcelas.Poblacion'),
        ),
    ]
