# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-24 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0019_auto_20190118_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
