# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0020_parcela_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
