# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-31 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0021_estado_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='localizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
