# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-04 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0022_auto_20190131_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['propietario', 'poligono'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
    ]
