# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-05 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0023_auto_20190204_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='poblacionesfavoritas',
            name='superfavorito',
            field=models.BooleanField(default=False),
        ),
    ]
