# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-05 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0024_poblacionesfavoritas_superfavorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poblacionesfavoritas',
            name='superfavorito',
        ),
    ]
