# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-05 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0025_remove_poblacionesfavoritas_superfavorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='poblacionesfavoritas',
            name='superfavorita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poblacionsuperfav', to='parcelas.Poblacion'),
        ),
    ]
