# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-11 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelas', '0027_auto_20190208_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectortrabajo',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='sector_usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
