# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-09 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
        ('parcelas', '0028_sectortrabajo_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='poseedor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poseedor', to='terceros.Terceros'),
        ),
    ]
