# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0029_parcela_poseedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='ref_catastral',
            field=models.TextField(blank=True, help_text='Se autocompleta', null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='coordinates',
            field=models.TextField(blank=True, help_text='Se autocompleta', null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='kml',
            field=models.TextField(blank=True, help_text='Se autocompleta', null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='localizacion',
            field=models.TextField(blank=True, help_text='Se autocompleta', null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='url',
            field=models.TextField(blank=True, help_text='Se autocompleta', null=True),
        ),
    ]
