# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0030_auto_20190410_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='propietario',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propietario', to='parcelas.Propietario'),
        ),
    ]
