# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0031_auto_20190411_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='poblacion',
        ),
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['poseedor', 'poligono'], 'permissions': (('acceder_parcelas', 'Puede acceder a la app de parcelas'),), 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='propietario',
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
    ]
