# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
        ('parcelas', '0032_auto_20190411_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['poligono'], 'permissions': (('acceder_parcelas', 'Puede acceder a la app de parcelas'),), 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='poseedor',
        ),
        migrations.AddField(
            model_name='parcela',
            name='propietario',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='terceros.Terceros'),
        ),
    ]
